{{ $fullname := include "dan-tvstack-bdd.fullname" .}}
{{ if .Values.bdd.schedule }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ template "dan-tvstack-bdd.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"    
spec:
  schedule: "{{ .Values.bdd.schedule }}"
  successfulJobsHistoryLimit: {{ default 10 .Values.bdd.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 10 .Values.bdd.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      annotations:
        {{- range $key, $val := .Values.deploy }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}            
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ template "dan-tvstack-bdd.fullname" . }}            
        spec:
          serviceAccountName: "{{ .Release.Name }}-sa"      
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["./initiate_deployment.sh", {{ .Values.deploy.brigadeCommitSha | quote }}, {{ .Values.image.tag | quote }}, {{ .Values.env | quote }}]
          restartPolicy: Never
{{ end }}