apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: "dan-tvstack-bdd-service-account"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}-sa"
